### ISSUE TITLE
energyplus error

### ISSUE THREAD

**Issue by flag2freefish** [airboxlab/rllib-energyplus#4]
when i run eplaunch.exe with model.idf and LUX_LU_Luxembourg.AP.065900_TMYx.2004-2018.epw, it shows that "**  Fatal  ** checkSetpointNodesAtEnd: At least one node does not have a setpoint attached, neither via a SetpointManager, EMS:Actuator, or API".
here is the log.
Program Version,EnergyPlus, Version 23.1.0-87ed9199d4, YMD=2023.05.16 15:15,
   ************* Beginning Zone Sizing Calculations
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=MILIANA
   **   ~~~   ** ..Weather File Location=Tampa International Ap FL USA TMY3 WMO#=722110
   **   ~~~   ** ..due to location differences, Latitude difference=[8.33] degrees, Longitude difference=[84.76] degrees.
   **   ~~~   ** ..Time Zone difference=[6.0] hour(s), Elevation difference=[99.16] percent, [709.00] meters.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON DISCRETE", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON DISCRETE 3", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS OFF DISCRETE", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON CONTINUOUS", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON DISCRETE 4", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON DISCRETE 5", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** ProcessScheduleInput: Schedule:Constant="ALWAYS ON DISCRETE 6", Blank Schedule Type Limits Name input -- will not be validated.
   ** Warning ** GetHTSurfaceData: Surfaces with interface to Ground found but no "Ground Temperatures" were input.
   **   ~~~   ** Found first in surface=SURFACE 6
   **   ~~~   ** Defaults, constant throughout the year of (18.0) will be used.
   ** Warning ** CheckUsedConstructions: There are 25 nominally unused constructions in input.
   **   ~~~   ** For explicit details on each unused construction, use Output:Diagnostics,DisplayExtraWarnings;
   ** Warning ** GetSimpleAirModelInputs: ZoneInfiltration:DesignFlowRate="TZ_AMPHITHEATER 189.1-2009 - SECSCHL - AUDITORIUM - CZ4-8 INFILTRATION 77.0 PERCENT REDUCTION", Design Flow Rate Calculation Method specifies Flow Rate per Exterior Surface Area, but Exterior Surface Area = 0.  0 Infiltration will result.
   ** Severe  ** UpdateZoneSizing: Cooling supply air temperature (calculated) within 2C of zone temperature
   **   ~~~   ** ...check zone thermostat set point and design supply air temperatures
   **   ~~~   ** ...zone name = TZ_AMPHITHEATER
   **   ~~~   ** ...design sensible cooling load = 485247.45 W
   **   ~~~   ** ...thermostat set point temp    = 0.000 C
   **   ~~~   ** ...zone temperature             = 14.025 C
   **   ~~~   ** ...supply air temperature       = 14.000 C
   **   ~~~   ** ...temperature difference       = -2.49369E-002 C
   **   ~~~   ** ...calculated volume flow rate  = 4140059.27874 m3/s
   **   ~~~   ** ...calculated mass flow rate    = 4982363.74891 kg/s
   ************* Beginning System Sizing Calculations
   ************* Beginning Plant Sizing Calculations
   ** Warning ** GetOAControllerInputs: Controller:MechanicalVentilation="CONTROLLER MECHANICAL VENTILATION 1"
   **   ~~~   ** Cannot locate a matching DesignSpecification:ZoneAirDistribution object for Zone="TZ_AMPHITHEATER".
   **   ~~~   ** Using default zone air distribution effectiveness of 1.0 for heating and cooling.
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   ** Warning ** CalcOAController: Minimum OA fraction > Mechanical Ventilation Controller request for Controller:OutdoorAir=CONTROLLER OUTDOOR AIR 1, Min OA fraction is used.
   **   ~~~   ** This may be overriding desired ventilation controls. Check inputs for Minimum Outdoor Air Flow Rate, Minimum Outdoor Air Schedule Name and Controller:MechanicalVentilation
   **   ~~~   ** Minimum OA fraction = 1.0000, Mech Vent OA fraction = 0.4883
   **   ~~~   **  Environment=2020, at Simulation time=01/01 09:00 - 09:15
   ** Warning ** Missing 'Temperature Setpoint' for node named named 'NODE 3'.
   **  Fatal  ** checkSetpointNodesAtEnd: At least one node does not have a setpoint attached, neither via a SetpointManager, EMS:Actuator, or API
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=UpdateZoneSizing: Cooling supply air temperature (calculated) within 2C of zone temperature
   *************
   ************* ===== Recurring Error Summary =====
   ************* The following recurring error messages occurred.
   *************
   *************  ** Warning ** Controller:OutdoorAir="CONTROLLER OUTDOOR AIR 1": Min OA fraction > Mechanical ventilation OA fraction, continues...
   *************  **   ~~~   **   This error occurred 35285 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=1.000000  Min=1.000000
   *************
   *************
   ************* ===== Final Error Summary =====
   ************* The following error categories occurred.  Consider correcting or noting.
   ************* Nominally Unused Constructions
   ************* ..The nominally unused constructions warning is provided to alert you to potential conditions that can cause
   ************* ..extra time during simulation. Each construction is calculated by the algorithm indicated in the HeatBalanceAlgorithm
   ************* ..object. You may remove the constructions indicated (when you use the DisplayExtraWarnings option).
   *************
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 11 Warning; 1 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 35299 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  2.75sec

plus
when i run run.py, finally, the same error occur.
part python log
Updating Shadowing Calculations, Start Date=10/08/2020
Continuing Simulation at 10/08/2020 for 2020
Updating Shadowing Calculations, Start Date=10/28/2020
Continuing Simulation at 10/28/2020 for 2020
Updating Shadowing Calculations, Start Date=11/17/2020
Continuing Simulation at 11/17/2020 for 2020
Updating Shadowing Calculations, Start Date=12/07/2020
Continuing Simulation at 12/07/2020 for 2020
Updating Shadowing Calculations, Start Date=12/27/2020
Continuing Simulation at 12/27/2020 for 2020
**FATAL:checkSetpointNodesAtEnd: At least one node does not have a setpoint attached, neither via a SetpointManager, EMS:Actuator, or API
EnergyPlus Run Time=00hr 00min  2.93sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.

**Comment by flag2freefish** [comment]
thank you for your apply. so, how can I solve this question?

> Hi @flag2freefish,
> 
> The first error you get is expected: the setpoint manager for `Node 3` (supply air outlet) was intentionally removed so policy decision don't get overridden by it. The fact that this happens during training is weird though. It seems to happen only on last simulation timestep; there could be an issue there.

**Comment by flag2freefish** [comment]
thank you for your apply. so, how can I solve this question?
and there are the idf file, weather file and err log file which I run it on windows 11.

**Comment by antoine-galataud** [comment]
I just tested on a fresh env and couldn't reproduce the issue. There can be several differences between your env and mine, including the OS, Linux on my side. 
Do you have the opportunity to test on a Linux VM ? I could also provide a docker image for this, this would probably help align all dependencies.

**Comment by antoine-galataud** [comment]
@flag2freefish I've created a Dockerfile you can use to build an image and run a training in a container.

Pull the branch from #5 to get the Dockerfile, then build the image:

```
docker build . -t rllib-energyplus
```

Start a container:

```
docker run --rm --name rllib-energyplus -it rllib-energyplus
```

Start the training in the container:

```
cd /root/rllib-energyplus
python3 run.py --idf model.idf --epw LUX_LU_Luxembourg.AP.065900_TMYx.2004-2018.epw --framework torch
```

**Comment by flag2freefish** [comment]
Thank you so much
