### ISSUE TITLE
Premature E+ simulation termination if rllib run as non-annual

### ISSUE THREAD

**Issue by sunchaesk** [airboxlab/rllib-energyplus#9]
I have noticed that if rllib is not executed as an annual simulation for energyplus, the simulation will often terminate without properly executing the simulations.

This seems to happen at random but never happens if the '-a' (annual) flag is passed into energyplus. I also haven't noticed this behaviour when running just energyplus outside of rllib.
![image](https://github.com/airboxlab/rllib-energyplus/assets/47470853/7a733f0c-d266-49e7-bd62-55d0b3e28d1f)

Also on the screenshot, it seems to suddenly start simulation for 7/21.

Thanks

**Comment by antoine-galataud** [comment]
Hi @sunchaesk,

I see 2 potential explanations for what you are observing:
- Ray RLlib has an environment checking mechanism that will execute only 1 step in an environment to make sure it's valid. In present case, that means E+ will be spawned and executed for only 1 control timestep, then the env is reset which causes all remaining E+ time steps to be executed only to properly end the run. This can be disabled using `"disable_env_checking": True` in Ray configuration.
- The jump you see in simulation start dates corresponds to sizing periods. At first, E+ will perform sizing using days specified in design days. Running simulation during these days can be disabled too, by editing your IDF and setting the parameter `Run Simulation for Sizing Periods` in `SimulationControl` to `No`.

**Comment by sunchaesk** [comment]
Thanks a lot.
I modified my idf on the `Run Simulation for Sizing Periods` and it fixed my issue
